services:
  tor-browser:
    hostname: "Tor Browser"
    build: .
    container_name: tor-browser
    ports:
      # Bind strictly to the requested host IP and port
      - "${HOST_ADDRESS:-127.0.0.1}:5800:5800"
      - "${HOST_ADDRESS:-127.0.0.1}:5801:5801"
    environment:
      - TZ=Europe/Rome
      - VNC_PASSWORD  # Forwards it from host or .env file
      - EXPOSE_PROXY=${EXPOSE_PROXY:-true}
      - SN_CERT=${SN_CERT:-localhost}
    # Web browsers heavily utilize shared memory. The Docker default (64MB)
    # will cause Tor to frequently crash. 1GB prevents this.
    shm_size: "3g"
    restart: unless-stopped

